services:
  bot_todo_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_todo_bot
    env_file:
    - .env
    environment:
      NODE_ENV: production
      BACKEND_URL: http://todo_backend:3000/api
    networks:
      awl_network:
        aliases:
        - telegram_todo_bot
    restart: unless-stopped

networks:
  awl_network:
    external: true
